import { useState } from "react";
import api from "../services/api";

function RecruiterInterviews() {
  const [form, setForm] = useState({ application_id: "", interview_date: "", interview_mode: "", status: "" });
  const [interviewId, setInterviewId] = useState(""); const [newStatus, setNewStatus] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const schedule = async (event) => { event.preventDefault(); setError(""); setMessage(""); setLoading(true); try { const response = await api.post("/recruiter/interviews", { ...form, application_id: Number(form.application_id) }); setMessage(response.data.message || "Interview scheduled successfully."); setForm({ application_id: "", interview_date: "", interview_mode: "", status: "" }); } catch (e) { setError(e.response?.data?.message || "Unable to schedule interview."); } finally { setLoading(false); } };
  const update = async (event) => { event.preventDefault(); setError(""); setMessage(""); try { const response = await api.put(`/recruiter/interviews/${interviewId}`, { status: newStatus }); setMessage(response.data.message || "Interview updated successfully."); setInterviewId(""); setNewStatus(""); } catch (e) { setError(e.response?.data?.message || "Unable to update interview."); } };
  return <div><h1>Interviews</h1><p>The backend does not provide a recruiter interview-list endpoint. Schedule interviews here or update one using its ID.</p>{message && <p>{message}</p>}{error && <p role="alert">{error}</p>}<h2>Schedule Interview</h2><form onSubmit={schedule}><input name="application_id" type="number" min="1" placeholder="Application ID" value={form.application_id} onChange={change} required /><br /><label>Interview date and time <input name="interview_date" type="datetime-local" value={form.interview_date} onChange={change} required /></label><br /><input name="interview_mode" placeholder="Interview mode (e.g. Online)" value={form.interview_mode} onChange={change} required /><br /><input name="status" placeholder="Status" value={form.status} onChange={change} required /><br /><button disabled={loading}>{loading ? "Scheduling..." : "Schedule Interview"}</button></form><h2>Update Interview Status</h2><form onSubmit={update}><input type="number" min="1" placeholder="Interview ID" value={interviewId} onChange={(e) => setInterviewId(e.target.value)} required /><br /><input placeholder="New status" value={newStatus} onChange={(e) => setNewStatus(e.target.value)} required /><br /><button>Update Status</button></form></div>;
}
export default RecruiterInterviews;
